service: origin
frameworkVersion: '3'
useDotenv: true

plugins:
  - serverless-offline
  - serverless-plugin-ifelse

custom:
  isOffline: ${env:IS_OFFLINE, "false"}
  serverlessIfElse:
    - If: '"${self:custom.isOffline}" != "true"'
      Exclude:
        - functions.endpoint.handler
        - provider.environment.CODESPACE_NAME
      ElseExclude:
        - functions.endpoint.image

provider:
  name: aws
  region: eu-central-1

  environment:
    CODESPACE_NAME: ${env:CODESPACE_NAME, ""}
    ENDPOINT_URL_ORIGIN: ${env:ENDPOINT_URL_ORIGIN, ""}
    ENDPOINT_URL_AUTHENTICATION: ${env:ENDPOINT_URL_AUTHENTICATION, ""}
    ENDPOINT_URL_EMAIL: ${env:ENDPOINT_URL_EMAIL, ""}
    ENDPOINT_URL_IAM: ${env:ENDPOINT_URL_IAM, ""}
    ENDPOINT_URL_REGISTRATION: ${env:ENDPOINT_URL_REGISTRATION, ""}
  ecr:
    images:
      appimage:
        path: ./

functions:
  endpoint:
    image:
      name: appimage
      command:
        - dist/app.handler
    handler: dist/app.handler
    events:
      - httpApi:
          path: '*'
          method: '*'
