POST http://localhost:3010/submit?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImVtYWlsIjoic2NoZXR0QHNuZWsuYXQifSwic2NvcGUiOm51bGwsInR5cGUiOiJwYXNzd29yZF9yZXNldCIsImlhdCI6MTY2NDQ0MjI2NywiZXhwIjoxNjY3MDM0MjY3LCJhdWQiOiIiLCJpc3MiOiJzbmVrLTAiLCJzdWIiOiJkZWU1YjM1MS1kMzA2LTQyZWEtOGVhZi0wMWE2OTg5YTZlMmQiLCJqdGkiOiIwZmE2Y2NkYS01Mzg1LTQ4MzItYWI3YS0yZTNjMWViNTY3NDgifQ.kk4QRU0SPS7r1gUXV_MtnadotuUhUQpjZ_3-bdpGXPI HTTP/1.1
content-type: application/json

{
    "password": "new"
}

###

GET http://localhost:3010/submit?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImVtYWlsIjoic2NoZXR0QHNuZWsuYXQifSwic2NvcGUiOm51bGwsInR5cGUiOiJwYXNzd29yZF9yZXNldCIsImlhdCI6MTY2NDM5ODY1NiwiZXhwIjoxNjY2OTkwNjU2LCJhdWQiOiIiLCJpc3MiOiJzbmVrLTAiLCJzdWIiOiJiZWMyMGJhMC0zMjY0LTRjOTUtYTZlZi1lZDMzN2YwZGRlMjEiLCJqdGkiOiI2ZDMwMDAyMi0zMzE3LTRhODAtYTI2ZC00YTQxNjU2MzA3NmMifQ.Nnw02YAaGZhimKXtO1gYoJdQEG4tQK-35gtFh6TQEzM HTTP/1.1